version: "3.8"
services:
  postgres_log:
    build:
      context: postgres_log
      dockerfile: Dockerfile
    ports:
      - '5433:5432'
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3