/**
 * Engines execute stages of the data pipeline generated by DataSQRL.
 * DataSQRL differentiates multiple types of engines like data stores, logs, stream
 * processing, and servers.
 * Engines have capabilities (i.e. the types of computation they can execute or how they
 * can represent data).
 *
 * This package contains the implementations of the engines DataSQRL supports.
 */
package com.datasqrl.engine;