/*
 * Copyright © 2021 DataSQRL (contact@datasqrl.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Engines execute stages of the data pipeline generated by DataSQRL. DataSQRL differentiates
 * multiple types of engines like data stores, logs, stream processing, and servers. Engines have
 * capabilities (i.e. the types of computation they can execute or how they can represent data).
 *
 * <p>This package contains the implementations of the engines DataSQRL supports.
 */
package com.datasqrl.engine;
