---
version: "1"
datasets:
- name: "coordinate-resolution"
  tables:
  - name: "usstates"
    partial_schema: false
    columns:
    - name: "state"
      type: "STRING"
      tests:
      - "not_null"
    - name: "abbreviation"
      type: "STRING"
      tests:
      - "not_null"