version: "3.8"
services:
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datasqrl
    ports:
      - '5432:5432'
    volumes:
      #      - db:/var/lib/postgresql/data
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql

  flink-jobmanager:
    image: flink:1.16.1-scala_2.12-java11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    volumes:
      - /Users/henneberger/sqrl/sqrl-examples/udf/data:/Users/henneberger/sqrl/sqrl-examples/udf/data


  flink-taskmanager:
    image: flink:1.16.1-scala_2.12-java11
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 1
    volumes:
      - /Users/henneberger/sqrl/sqrl-examples/udf/data:/Users/henneberger/sqrl/sqrl-examples/udf/data
  servlet:
    image: eclipse-temurin:11
    command: java -jar vertx-server.jar
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - ./model.json:/model.json
      - ./config.json:/config.json
      - ./vertx-server.jar:/vertx-server.jar

volumes:
  db:
    driver: local
