---
version: "1"
datasets:
- name: "datasqrl-central"
  tables:
  - name: "submission"
    partial_schema: false
    columns:
    - name: "name"
      type: "STRING"
      tests:
      - "not_null"
    - name: "version"
      type: "STRING"
      tests:
      - "not_null"
    - name: "latestStable"
      type: "BOOLEAN"
      tests:
        - "not_null"
    - name: "license"
      type: "STRING"
    - name: "repository"
      type: "STRING"
    - name: "homepage"
      type: "STRING"
    - name: "documentation"
      type: "STRING"
    - name: "readme"
      type: "STRING"
    - name: "description"
      type: "STRING"
    - name: "file"
      type: "STRING"
      tests:
      - "not_null"
    - name: "hash"
      type: "STRING"
      tests:
      - "not_null"
    - name: "authorid"
      type: "STRING"
      tests:
      - "not_null"
    - name: "submissionTime"
      type: "DATETIME"
      tests:
      - "not_null"
    - name: "files"
      columns:
      - name: "filename"
        type: "STRING"
        tests:
        - "not_null"
      - name: "filesize"
        type: "INTEGER"
        tests:
        - "not_null"
