name: "product"
schema_version: 1
partial_schema: false
columns:
  - name: "productid"
    type: "INTEGER"
    tests:
      - "not_null"
  - name: "name"
    type: "STRING"
    tests:
      - "not_null"
  - name: "description"
    type: "STRING"
    tests:
      - "not_null"
  - name: "category"
    type: "STRING"
    tests:
      - "not_null"
