---
name: "applications"
schema_version: "1"
partial_schema: false
columns:
- name: "id"
  type: "INTEGER"
  tests:
  - "not_null"
- name: "customer_id"
  type: "INTEGER"
  tests:
  - "not_null"
- name: "loan_type_id"
  type: "INTEGER"
  tests:
  - "not_null"
- name: "amount"
  type: "FLOAT"
  tests:
  - "not_null"
- name: "duration"
  type: "INTEGER"
  tests:
  - "not_null"
- name: "application_date"
  type: "DATETIME"
  tests:
  - "not_null"
- name: "updated_at"
  type: "DATETIME"
  tests:
  - "not_null"
