---
name: "application_updates"
schema_version: "1"
partial_schema: false
columns:
- name: "loan_application_id"
  type: "INTEGER"
  tests:
  - "not_null"
- name: "status"
  type: "STRING"
  tests:
  - "not_null"
- name: "message"
  type: "STRING"
  tests:
  - "not_null"
- name: "timestamp"
  type: "DATETIME"
  tests:
  - "not_null"
