version: 1

tables:
  - name: PoS
    description: All registered and active Point-Of-Service for processing CC-transactions
    source:
      - type: file
        name: pos.json
    columns:
      - name: pos_id
        tests:
          - type: integer
          - unique
          - not_null
      - name: merchant_id
        tests:
          - type: integer
          - not_null
          - relationships:
             to: Merchant
             field: merchant_id
             name: merchant
      - name: registered_on
        tests:
          - type: timestamp
          - not_null
      - name: online
        tests:
          - type: boolean
          - not_null
      - name: location
        tests:
          - type: geopoint
          - not_null
  - name: Merchant
    description: All Merchant that have registered PoS
    source:
      - type: file
        name: merchant.csv
    columns:
      - name: merchant_id
        tests:
          - type: integer
          - not_null
          - unique
      - name: name
        tests:
          - type: string
          - not_null
      - name: category
        tests:
          - type: string
          - not_null
  - name: Transaction
    description: Credit Card Transactions
    source:
      - type: file
        name: transactions.csv
    columns:
      - name: tx_id
        tests:
          - type: uuid
          - not_null
          - unique
      - name: cc_number
        tests:
          - type: integer
          - not_null
      - name: pos_id
        tests:
          - type: integer
          - not_null
          - relationships:
             to: PoS
             field: pos_id
             name: pos
      - name: amount
        tests:
          - type: Number
          - not_null
      - name: contested
        tests:
          - type: boolean
      - name: canceled
        tests:
          - type: boolean
