/*
 * Copyright (c) 2021, DataSQRL. All rights reserved. Use is subject to license terms.
 */
package com.datasqrl.error;

public enum ErrorCode implements ErrorLabel {

  IMPORT_NAMESPACE_CONFLICT,
  IMPORT_CANNOT_BE_ALIASED,
  IMPORT_STAR_CANNOT_HAVE_TIMESTAMP,
  IMPORT_IN_HEADER,
  INVALID_IMPORT,
  INVALID_EXPORT,
  INVALID_HINT,
  INVALID_TABLE_FUNCTION_ARGUMENTS,
  INVALID_SQRL_DEFINITION,
  INVALID_SQRL_ADD_COLUMN,
  BASETABLE_ONLY_ERROR,
  MISSING_DEST_TABLE,
  TIMESTAMP_COLUMN_MISSING,
  TIMESTAMP_COLUMN_EXPRESSION,
  PATH_NOT_WRITABLE,
  MISSING_FIELD,
  MISSING_TABLE,
  ORDINAL_NOT_SUPPORTED,
  CANNOT_SHADOW_RELATIONSHIP,
  TO_MANY_PATH_NOT_ALLOWED,
  NESTED_DISTINCT_ON,
  CANNOT_RESOLVE_TABLESINK,
  IOEXCEPTION,
  DISTINCT_ON_TIMESTAMP,
  WRONG_TABLE_TYPE,
  WRONG_INTERVAL_JOIN,
  CONFIG_EXCEPTION,
  PRIMARY_KEY_NULLABLE,
  MULTIPLE_PRIMARY_KEY,
  TABLE_LOCKED,
  SCHEMA_ERROR,
  TABLE_NOT_MATERIALIZE,
  FUNCTION_EXISTS,
  NOT_YET_IMPLEMENTED,
  ROWTIME_IS_NULLABLE;

  @Override
  public String getLabel() {
    return toString();
  }
}
