/*
 * Copyright © 2021 DataSQRL (contact@datasqrl.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datasqrl.graphql.config;

import io.vertx.core.json.JsonObject;

/**
 * Converter class for SwaggerConfig. This class is typically generated by Vert.x codegen, but we
 * provide a simple implementation for configuration conversion.
 */
public class SwaggerConfigOptionsConverter {

  public static void fromJson(JsonObject json, SwaggerConfig obj) {
    if (json.getValue("enabled") instanceof Boolean) {
      obj.setEnabled((Boolean) json.getValue("enabled"));
    } else {
      obj.setEnabled(true);
    }
    if (json.getValue("endpoint") instanceof String) {
      obj.setEndpoint((String) json.getValue("endpoint"));
    } else {
      obj.setEndpoint("/swagger");
    }
    if (json.getValue("uiEndpoint") instanceof String) {
      obj.setUiEndpoint((String) json.getValue("uiEndpoint"));
    } else {
      obj.setUiEndpoint("/swagger-ui");
    }
    if (json.getValue("title") instanceof String) {
      obj.setTitle((String) json.getValue("title"));
    } else {
      obj.setTitle("DataSQRL REST API");
    }
    if (json.getValue("description") instanceof String) {
      obj.setDescription((String) json.getValue("description"));
    } else {
      obj.setDescription("Auto-generated REST API documentation for DataSQRL endpoints");
    }
    if (json.getValue("version") instanceof String) {
      obj.setVersion((String) json.getValue("version"));
    } else {
      obj.setVersion("1.0.0");
    }
    if (json.getValue("contact") instanceof String) {
      obj.setContact((String) json.getValue("contact"));
    } else {
      obj.setContact("DataSQRL");
    }
    if (json.getValue("contactUrl") instanceof String) {
      obj.setContactUrl((String) json.getValue("contactUrl"));
    } else {
      obj.setContactUrl("https://datasqrl.com");
    }
    if (json.getValue("contactEmail") instanceof String) {
      obj.setContactEmail((String) json.getValue("contactEmail"));
    } else {
      obj.setContactEmail("contact@datasqrl.com");
    }
    if (json.getValue("license") instanceof String) {
      obj.setLicense((String) json.getValue("license"));
    } else {
      obj.setLicense("Apache License 2.0");
    }
    if (json.getValue("licenseUrl") instanceof String) {
      obj.setLicenseUrl((String) json.getValue("licenseUrl"));
    } else {
      obj.setLicenseUrl("https://www.apache.org/licenses/LICENSE-2.0");
    }
  }

  public static void toJson(SwaggerConfig obj, JsonObject json) {
    json.put("enabled", obj.isEnabled());
    if (obj.getEndpoint() != null) {
      json.put("endpoint", obj.getEndpoint());
    }
    if (obj.getUiEndpoint() != null) {
      json.put("uiEndpoint", obj.getUiEndpoint());
    }
    if (obj.getTitle() != null) {
      json.put("title", obj.getTitle());
    }
    if (obj.getDescription() != null) {
      json.put("description", obj.getDescription());
    }
    if (obj.getVersion() != null) {
      json.put("version", obj.getVersion());
    }
    if (obj.getContact() != null) {
      json.put("contact", obj.getContact());
    }
    if (obj.getContactUrl() != null) {
      json.put("contactUrl", obj.getContactUrl());
    }
    if (obj.getContactEmail() != null) {
      json.put("contactEmail", obj.getContactEmail());
    }
    if (obj.getLicense() != null) {
      json.put("license", obj.getLicense());
    }
    if (obj.getLicenseUrl() != null) {
      json.put("licenseUrl", obj.getLicenseUrl());
    }
  }
}
