/*
 * Copyright © 2021 DataSQRL (contact@datasqrl.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datasqrl.graphql.config;

import io.vertx.core.json.JsonObject;

/**
 * Converter class for SwaggerConfig. This class is typically generated by Vert.x codegen, but we
 * provide a simple implementation for configuration conversion.
 */
public class SwaggerConfigOptionsConverter {

  public static void fromJson(JsonObject json, SwaggerConfig obj) {
    SwaggerConfig.SwaggerConfigBuilder builder = SwaggerConfig.builder();

    if (json.getValue("enabled") instanceof Boolean) {
      builder.enabled((Boolean) json.getValue("enabled"));
    }
    if (json.getValue("endpoint") instanceof String) {
      builder.endpoint((String) json.getValue("endpoint"));
    }
    if (json.getValue("uiEndpoint") instanceof String) {
      builder.uiEndpoint((String) json.getValue("uiEndpoint"));
    }
    if (json.getValue("title") instanceof String) {
      builder.title((String) json.getValue("title"));
    }
    if (json.getValue("description") instanceof String) {
      builder.description((String) json.getValue("description"));
    }
    if (json.getValue("version") instanceof String) {
      builder.version((String) json.getValue("version"));
    }
    if (json.getValue("contact") instanceof String) {
      builder.contact((String) json.getValue("contact"));
    }
    if (json.getValue("contactUrl") instanceof String) {
      builder.contactUrl((String) json.getValue("contactUrl"));
    }
    if (json.getValue("contactEmail") instanceof String) {
      builder.contactEmail((String) json.getValue("contactEmail"));
    }
    if (json.getValue("license") instanceof String) {
      builder.license((String) json.getValue("license"));
    }
    if (json.getValue("licenseUrl") instanceof String) {
      builder.licenseUrl((String) json.getValue("licenseUrl"));
    }

    SwaggerConfig built = builder.build();
    obj.setEnabled(built.isEnabled());
    obj.setEndpoint(built.getEndpoint());
    obj.setUiEndpoint(built.getUiEndpoint());
    obj.setTitle(built.getTitle());
    obj.setDescription(built.getDescription());
    obj.setVersion(built.getVersion());
    obj.setContact(built.getContact());
    obj.setContactUrl(built.getContactUrl());
    obj.setContactEmail(built.getContactEmail());
    obj.setLicense(built.getLicense());
    obj.setLicenseUrl(built.getLicenseUrl());
  }

  public static void toJson(SwaggerConfig obj, JsonObject json) {
    json.put("enabled", obj.isEnabled());
    if (obj.getEndpoint() != null) {
      json.put("endpoint", obj.getEndpoint());
    }
    if (obj.getUiEndpoint() != null) {
      json.put("uiEndpoint", obj.getUiEndpoint());
    }
    if (obj.getTitle() != null) {
      json.put("title", obj.getTitle());
    }
    if (obj.getDescription() != null) {
      json.put("description", obj.getDescription());
    }
    if (obj.getVersion() != null) {
      json.put("version", obj.getVersion());
    }
    if (obj.getContact() != null) {
      json.put("contact", obj.getContact());
    }
    if (obj.getContactUrl() != null) {
      json.put("contactUrl", obj.getContactUrl());
    }
    if (obj.getContactEmail() != null) {
      json.put("contactEmail", obj.getContactEmail());
    }
    if (obj.getLicense() != null) {
      json.put("license", obj.getLicense());
    }
    if (obj.getLicenseUrl() != null) {
      json.put("licenseUrl", obj.getLicenseUrl());
    }
  }
}
