version: "3.8"
services:
  database:
   build:
     context: postgres
     dockerfile: Dockerfile
   restart: always
   entrypoint: ["/bin/bash","-c"]
   command:
     - |
       bin/yugabyted start --ysql_port 5432
       sleep 5
       bin/ysqlsh -h `hostname -i` -p 5432 -c '\x' -c "CREATE DATABASE datasqrl WITH COLOCATION = true;"
       bin/ysqlsh -h `hostname -i` -p 5432 -d "datasqrl" <<EOF
       \x
       CREATE ROLE postgres WITH LOGIN SUPERUSER PASSWORD 'postgres';
       EOF
       YSQL_PASSWORD="postgres" bin/ysqlsh -h `hostname -i` -p 5432 -d "datasqrl" -U "postgres" -f /home/yugabyte/docker-entrypoint-initdb.d/database-schema.sql
       tail -f /dev/null
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=datasqrl
   ports:
     - '5432:5432'
     - '15433:15433'
     - '9042:9042'
     - '7001:7000'
   volumes:
     - ./postgres/database-schema.sql:/home/yugabyte/docker-entrypoint-initdb.d/database-schema.sql
