version: 1

tables:
  - name: Customer
    description: customer records from online shop
    source:
      - type: file
        name: customer.csv
    columns:
      - name: customerid
        description: the unique id for each customer
        type: integer
        tests:
          - unique
          - not_null
      - name: email
        type: string
        tests:
          - not_null
      - name: name
        type: string
  - name: Product
    description: Catalog of all products
    source:
      - type: file
        name: product.csv
    columns:
      - name: productid
        type: integer
        tests:
          - unique
          - not_null
      - name: name
        type: string
        tests:
          - not_null
      - name: description
        type: string
      - name: category
        type: string
  - name: Orders
    description: Order records placed online
    source:
      - type: file
        name: orders.json
    columns:
      - name: id
        type: integer
        tests:
          - unique
          - not_null
      - name: customerid
        type: integer
#        tests:
#         - relationships:
#             to: Customer
#             field: customerid
#             name: customer
      - name: time
        type: datetime
        tests:
          - not_null
      - name: entries
        columns:
          - name: productid
            type: integer
#            tests:
#              - relationships:
#                  to: Product
#                  field: productid
#                  name: product
          - name: quantity
            type: integer
            tests:
              - not_null
          - name: unit_price
            type: float
            tests:
              - not_null
          - name: discount
            type: float
