name: Maven build and test

on:
  push:
    branches: [main, sqrl-0.5.x, v0.5.9-release]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Los_Angeles"
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build SQRL
        env:
          DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
        run: mvn -T 1 -B -U -e clean package
