name: Build and test SQRL with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: read

    steps:
    - name: Setup Timezone
      uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "America/Los_Angeles"
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Generate settings.xml
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Download dependencies
      run: |
        mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies -T3

    - name: Build SQRL
      env:
        DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
      run: mvn -T 1 -B -U -e clean verify

    - name: Build Docker image
      run: docker build -t sqrl-test ./sqrl-tools

    - name: Run Docker container and execute tests
      working-directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/banking
      run: |
        docker run -i --rm -v $PWD:/build sqrl-test test loan.sqrl loan.graphqls --snapshot snapshots-loan --tests tests-loan
      continue-on-error: false

    - name: Test UDF
      working-directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/udf
      run: |
        docker run -i --rm -v $PWD:/build sqrl-test test myudf.sqrl --snapshot snapshots-myudf --tests tests-myudf
      continue-on-error: false

    - name: Check Docker return code
      run: |
        if [ $? -ne 0 ]; then
          echo "Test failed."
          exit 1
        else
          echo "Test passed."
        fi
