name: Latest Docker Build and Push

on:
  push:
    branches: [main, v0.5]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Los_Angeles"
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build DataSQRL
        run: mvn -B -U -T 1 -e clean install
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # Set up Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push sqrl-cli Dev
        uses: docker/build-push-action@v3
        with:
          context: sqrl-tools/sqrl-cli
          file: sqrl-tools/sqrl-cli/Dockerfile
          push: true
          tags: datasqrl/cmd:dev
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-vertx Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-server/sqrl-server-vertx
          file: sqrl-server/sqrl-server-vertx/Dockerfile
          push: true
          tags: datasqrl/sqrl-server:dev
          platforms: linux/amd64,linux/arm64