name: Latest Docker Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # Build DataSQRL (mvn package -DskipTests)
      - name: Build DataSQRL
        run: mvn -B -U -T 6 -e clean install --no-transfer-progress -DskipTests=true

      # Set up Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Copy JAR files
        run: |
          cp sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar/target/flink-job.jar sqrl-tools/sqrl-cli/target/flink-job.jar
          cp sqrl-execute/sqrl-execute-http/sqrl-execute-http-vertx/target/vertx-server.jar sqrl-tools/sqrl-cli/target/vertx-server.jar
      # Build docker (cd sqrl-tools/sqrl-cli; docker build -t datasqrl/cmd . )
      - name: Build and Push sqrl-cli Dev
        uses: docker/build-push-action@v3
        with:
          context: sqrl-tools/sqrl-cli
          file: sqrl-tools/sqrl-cli/Dockerfile
          push: true
          tags: datasqrl/cmd:dev
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-http-vertx Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-http/sqrl-execute-http-vertx
          file: sqrl-execute/sqrl-execute-http/sqrl-execute-http-vertx/Dockerfile
          push: true
          tags: datasqrl/engine-vertx:dev
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-http-aws-lambda Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-http/sqrl-execute-http-aws-lambda
          file: sqrl-execute/sqrl-execute-http/sqrl-execute-http-aws-lambda/Dockerfile
          push: true
          tags: datasqrl/engine-aws-lambda:dev
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-flink-jar Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar
          file: sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar/Dockerfile
          push: true
          tags: datasqrl/engine-flink:dev
          platforms: linux/amd64,linux/arm64
