name: Latest Docker Build and Push

on:
  push:
    branches: [main, sqrl-0.5.x, v0.5.9-release]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Los_Angeles"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Generate settings.xml
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                <servers>
                  <server>
                    <id>github</id>
                    <username>${{ github.actor }}</username>
                    <password>${{ secrets.GITHUB_TOKEN }}</password>
                  </server>
                </servers>
              </settings>" > ~/.m2/settings.xml

      - name: Extract Project Version
        id: get-version
        run: echo "VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)" >> $GITHUB_ENV

      - name: Build SQRL
        env:
          DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
        run: mvn -T 1 -B -U -e clean package

      # Set up Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker Tags
        id: set-tags
        run: |
          CMD_TAGS="datasqrl/cmd:v${VERSION}"
          SERVER_TAGS="datasqrl/sqrl-server:v${VERSION}"

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            CMD_TAGS="$CMD_TAGS,datasqrl/cmd:dev"
            SERVER_TAGS="$SERVER_TAGS,datasqrl/sqrl-server:dev"
          fi

          echo "CMD_TAGS=$CMD_TAGS" >> $GITHUB_ENV
          echo "SERVER_TAGS=$SERVER_TAGS" >> $GITHUB_ENV

      - name: Build and Push sqrl-cli Dev
        uses: docker/build-push-action@v3
        with:
          context: sqrl-tools
          file: sqrl-tools/Dockerfile
          push: true
          tags: ${{ env.CMD_TAGS }}
          platforms: linux/amd64,linux/arm64

      - name: Build and Push sqrl-vertx Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-server/sqrl-server-vertx
          file: sqrl-server/sqrl-server-vertx/Dockerfile
          push: true
          tags: ${{ env.SERVER_TAGS }}
          platforms: linux/amd64,linux/arm64
