name: Latest Docker Build and Push

on:
  push:
    branches: [main, sqrl-0.5.x, v0.5.9-release]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    steps:
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Los_Angeles"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Extract Project Version
        id: get-version
        run: echo "VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)" >> $GITHUB_ENV

      - name: Build SQRL
        env:
          DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
        run: mvn -T 1 -B -U -e clean package

      # Set up Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker Tags
        id: set-tags
        run: |
          TAGS="datasqrl/cmd:${VERSION_TAG} datasqrl/sqrl-server:${VERSION}"

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="$TAGS datasqrl/cmd:dev datasqrl/sqrl-server:dev"
          fi

          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push sqrl-cli Dev
        uses: docker/build-push-action@v3
        with:
          context: sqrl-tools
          file: sqrl-tools/Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          platforms: linux/amd64,linux/arm64

      - name: Build and Push sqrl-vertx Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-server/sqrl-server-vertx
          file: sqrl-server/sqrl-server-vertx/Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          platforms: linux/amd64,linux/arm64