name: Release Docker Build and Push

on:
  release:
    types: [created]
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build SQRL
        run: mvn -B -U -e clean install --no-transfer-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Latest
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: datasqrl/cmd:latest
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-http-vertx Docker
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-http/sqrl-execute-http-vertx
          file: sqrl-execute/sqrl-execute-http/sqrl-execute-http-vertx/Dockerfile
          push: true
          tags: datasqrl/sqrl-execute-http-vertx:latest
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-flink-jar Docker
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar
          file: sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar/Dockerfile
          push: true
          tags: datasqrl/sqrl-execute-flink-jar:latest
          platforms: linux/amd64,linux/arm64
      - name: Tag and Push Docker Images
        if: ${{ github.event_name == 'release' }}
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          docker tag datasqrl/cmd:latest datasqrl/cmd:$TAG_NAME
          docker tag datasqrl/sqrl-execute-http-vertx:latest datasqrl/sqrl-execute-http-vertx:$TAG_NAME
          docker tag datasqrl/sqrl-execute-flink-jar:latest datasqrl/sqrl-execute-flink-jar:$TAG_NAME
          docker push datasqrl/cmd:$TAG_NAME
          docker push datasqrl/sqrl-execute-http-vertx:$TAG_NAME
          docker push datasqrl/sqrl-execute-flink-jar:$TAG_NAME
      - name: Create GitHub Release
        if: ${{ github.ref != 'refs/heads/main'}}
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}