name: PR Docker Build and Push to GitHub Packages

on:
  pull_request:

jobs:
  pr-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Los_Angeles"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Generate settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                <servers>
                  <server>
                    <id>github</id>
                    <username>${{ github.actor }}</username>
                    <password>${{ secrets.GITHUB_TOKEN }}</password>
                  </server>
                </servers>
              </settings>" > ~/.m2/settings.xml

      - name: Extract Project Version
        id: get-version
        run: echo "VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)" >> $GITHUB_ENV

      - name: Build SQRL
        env:
          DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
        run: mvn -T 1 -B -U -e clean package

      # Set up Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker Tags
        id: set-tags
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          CMD_TAG="ghcr.io/datasqrl/cmd:pr-${PR_NUMBER}"
          SERVER_TAG="ghcr.io/datasqrl/sqrl-server:pr-${PR_NUMBER}"

          echo "CMD_TAG=$CMD_TAG" >> $GITHUB_ENV
          echo "SERVER_TAG=$SERVER_TAG" >> $GITHUB_ENV

      - name: Build and Push sqrl-cli PR Image
        uses: docker/build-push-action@v3
        with:
          context: sqrl-tools
          file: sqrl-tools/Dockerfile
          push: true
          tags: ${{ env.CMD_TAG }}
          platforms: linux/amd64,linux/arm64

      - name: Build and Push sqrl-vertx PR Image
        uses: docker/build-push-action@v3
        with:
          context: sqrl-server/sqrl-server-vertx
          file: sqrl-server/sqrl-server-vertx/Dockerfile
          push: true
          tags: ${{ env.SERVER_TAG }}
          platforms: linux/amd64,linux/arm64
