name: Tag Docker Build and Push

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build SQRL
        run: mvn -B -U -T 6 -e clean install --no-transfer-progress -DskipTests=true

    # Set up Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build docker
      - name: Build and Push sqrl-cli Latest
        uses: docker/build-push-action@v3
        with:
          context: sqrl-tools/sqrl-cli
          file: sqrl-tools/sqrl-cli/Dockerfile
          push: true
          tags: datasqrl/cmd:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-http-vertx Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-http/sqrl-execute-http-vertx
          file: sqrl-execute/sqrl-execute-http/sqrl-execute-http-vertx/Dockerfile
          push: true
          tags: datasqrl/engine-vertx:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-http-aws-lambda Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-http/sqrl-execute-http-aws-lambda
          file: sqrl-execute/sqrl-execute-http/sqrl-execute-http-aws-lambda/Dockerfile
          push: true
          tags: datasqrl/engine-aws-lambda:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
      - name: Build and Push sqrl-execute-flink-jar Docker
        uses: docker/build-push-action@v3
        with:
          context: sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar
          file: sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar/Dockerfile
          push: true
          tags: datasqrl/engine-flink:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64